[tool.ruff]
target-version = "py311"
line-length = 120
exclude = ["migrations", ".venv"]

select = ["E", "F", "I", "UP", "B", "DJ", "C4", "RUF"]

ignore = ["E501"]

[tool.ruff.isort]
known-first-party = ["orders", "backend", "orders"]
force-sort-within-sections = true
combine-as-imports = true