name: 'Coverage Badge'
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  coverage-badge:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests with coverage
      run: |
        coverage run --source=backend manage.py test backend.test_views
        coverage report --format=total > coverage_total.txt
        
    - name: Show coverage
      run: |
        echo "=== COVERAGE REPORT ==="
        cat coverage_total.txt
        echo "======================="
        
        COVERAGE=$(cat coverage_total.txt | grep TOTAL | awk '{print $4}' | sed 's/%//')
        echo "Coverage: $COVERAGE%"
        
        # Определяем цвет бейджа
        if [ $COVERAGE -ge 80 ]; then
          COLOR="brightgreen"
        elif [ $COVERAGE -ge 60 ]; then
          COLOR="green"
        elif [ $COVERAGE -ge 40 ]; then
          COLOR="yellow"
        elif [ $COVERAGE -ge 20 ]; then
          COLOR="orange"
        else
          COLOR="red"
        fi
        
        echo "Badge URL: https://img.shields.io/badge/coverage-${COVERAGE}%25-${COLOR}"
        echo "You can manually update your README with this badge URL"
